################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../obj_micaz/Pacotes.o \
../obj_micaz/abc.o \
../obj_micaz/adc.o \
../obj_micaz/announcement.o \
../obj_micaz/autostart.o \
../obj_micaz/battery-sensor.o \
../obj_micaz/bootloader.o \
../obj_micaz/broadcast-announcement.o \
../obj_micaz/broadcast.o \
../obj_micaz/cc2420-arch.o \
../obj_micaz/cc2420.o \
../obj_micaz/cfs-eeprom.o \
../obj_micaz/chameleon-bitopt.o \
../obj_micaz/chameleon-raw.o \
../obj_micaz/chameleon.o \
../obj_micaz/channel.o \
../obj_micaz/checkpoint.o \
../obj_micaz/clock.o \
../obj_micaz/collect-link-estimate.o \
../obj_micaz/collect-neighbor.o \
../obj_micaz/collect.o \
../obj_micaz/compower.o \
../obj_micaz/contiki-micaz-main.o \
../obj_micaz/contikimac.o \
../obj_micaz/crc16.o \
../obj_micaz/csma.o \
../obj_micaz/ctimer.o \
../obj_micaz/cxmac.o \
../obj_micaz/dhcpc.o \
../obj_micaz/ds2401.o \
../obj_micaz/eeprom.o \
../obj_micaz/elfloader-avr.o \
../obj_micaz/elfloader.o \
../obj_micaz/energest.o \
../obj_micaz/etimer.o \
../obj_micaz/flash.o \
../obj_micaz/frame802154.o \
../obj_micaz/framer-802154.o \
../obj_micaz/framer-nullmac.o \
../obj_micaz/hc.o \
../obj_micaz/ifft.o \
../obj_micaz/init-net.o \
../obj_micaz/ipolite.o \
../obj_micaz/leds-arch.o \
../obj_micaz/leds.o \
../obj_micaz/list.o \
../obj_micaz/lpp.o \
../obj_micaz/mac.o \
../obj_micaz/memb.o \
../obj_micaz/mesh.o \
../obj_micaz/mmem.o \
../obj_micaz/mt.o \
../obj_micaz/mtarch.o \
../obj_micaz/mts300.o \
../obj_micaz/multihop.o \
../obj_micaz/neighbor-discovery.o \
../obj_micaz/netflood.o \
../obj_micaz/netstack.o \
../obj_micaz/node-id.o \
../obj_micaz/nullmac.o \
../obj_micaz/nullradio.o \
../obj_micaz/nullrdc-noframer.o \
../obj_micaz/nullrdc.o \
../obj_micaz/packetbuf.o \
../obj_micaz/packetqueue.o \
../obj_micaz/phase.o \
../obj_micaz/polite-announcement.o \
../obj_micaz/polite.o \
../obj_micaz/print-stats.o \
../obj_micaz/process.o \
../obj_micaz/procinit.o \
../obj_micaz/profile.o \
../obj_micaz/psock.o \
../obj_micaz/queuebuf.o \
../obj_micaz/random.o \
../obj_micaz/resolv.o \
../obj_micaz/rime.o \
../obj_micaz/rimeaddr.o \
../obj_micaz/rimestats.o \
../obj_micaz/ringbuf.o \
../obj_micaz/rmh.o \
../obj_micaz/route-discovery.o \
../obj_micaz/route.o \
../obj_micaz/rs232.o \
../obj_micaz/rtimer-arch.o \
../obj_micaz/rtimer.o \
../obj_micaz/rucb.o \
../obj_micaz/rudolph0.o \
../obj_micaz/rudolph1.o \
../obj_micaz/rudolph2.o \
../obj_micaz/runicast.o \
../obj_micaz/serial-line.o \
../obj_micaz/settings.o \
../obj_micaz/sicslowmac.o \
../obj_micaz/simple-udp.o \
../obj_micaz/slip.o \
../obj_micaz/slip_uart0.o \
../obj_micaz/spi.o \
../obj_micaz/stbroadcast.o \
../obj_micaz/stimer.o \
../obj_micaz/stunicast.o \
../obj_micaz/symtab-avr.o \
../obj_micaz/tcpdump.o \
../obj_micaz/tcpip.o \
../obj_micaz/timer.o \
../obj_micaz/timesynch.o \
../obj_micaz/timetable-aggregate.o \
../obj_micaz/timetable.o \
../obj_micaz/trickle.o \
../obj_micaz/uaodv-rt.o \
../obj_micaz/uaodv.o \
../obj_micaz/uip-debug.o \
../obj_micaz/uip-fw-drv.o \
../obj_micaz/uip-fw.o \
../obj_micaz/uip-neighbor.o \
../obj_micaz/uip-over-mesh.o \
../obj_micaz/uip-split.o \
../obj_micaz/uip-udp-packet.o \
../obj_micaz/uip.o \
../obj_micaz/uip_arp.o \
../obj_micaz/uiplib.o \
../obj_micaz/unicast.o \
../obj_micaz/watchdog.o \
../obj_micaz/xmac.o 


# Each subdirectory must supply rules for building sources it contributes

