################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../obj_z1/abc.o \
../obj_z1/adxl345.o \
../obj_z1/announcement.o \
../obj_z1/autostart.o \
../obj_z1/battery-sensor.o \
../obj_z1/broadcast-announcement.o \
../obj_z1/broadcast.o \
../obj_z1/button-sensor.o \
../obj_z1/cc2420-aes.o \
../obj_z1/cc2420-arch-sfd.o \
../obj_z1/cc2420-arch.o \
../obj_z1/cc2420.o \
../obj_z1/cfs-coffee.o \
../obj_z1/chameleon-bitopt.o \
../obj_z1/chameleon-raw.o \
../obj_z1/chameleon.o \
../obj_z1/channel.o \
../obj_z1/checkpoint-arch.o \
../obj_z1/checkpoint.o \
../obj_z1/clock.o \
../obj_z1/collect-link-estimate.o \
../obj_z1/collect-neighbor.o \
../obj_z1/collect.o \
../obj_z1/compower.o \
../obj_z1/contiki-z1-platform.o \
../obj_z1/contikimac.o \
../obj_z1/crc16.o \
../obj_z1/csma.o \
../obj_z1/ctimer.o \
../obj_z1/cxmac.o \
../obj_z1/dhcpc.o \
../obj_z1/elfloader-msp430.o \
../obj_z1/elfloader.o \
../obj_z1/energest.o \
../obj_z1/etimer.o \
../obj_z1/flash.o \
../obj_z1/frame802154.o \
../obj_z1/framer-802154.o \
../obj_z1/framer-nullmac.o \
../obj_z1/hc.o \
../obj_z1/i2cmaster.o \
../obj_z1/ifft.o \
../obj_z1/ipolite.o \
../obj_z1/leds-arch.o \
../obj_z1/leds.o \
../obj_z1/light-sensor.o \
../obj_z1/light-ziglet.o \
../obj_z1/list.o \
../obj_z1/lpm.o \
../obj_z1/lpp.o \
../obj_z1/mac.o \
../obj_z1/me.o \
../obj_z1/me_tabs.o \
../obj_z1/memb.o \
../obj_z1/mesh.o \
../obj_z1/mmem.o \
../obj_z1/msp430.o \
../obj_z1/mt.o \
../obj_z1/mtarch.o \
../obj_z1/multihop.o \
../obj_z1/neighbor-discovery.o \
../obj_z1/netflood.o \
../obj_z1/netstack.o \
../obj_z1/node-id.o \
../obj_z1/nullmac.o \
../obj_z1/nullradio.o \
../obj_z1/nullrdc-noframer.o \
../obj_z1/nullrdc.o \
../obj_z1/packetbuf.o \
../obj_z1/packetqueue.o \
../obj_z1/phase.o \
../obj_z1/polite-announcement.o \
../obj_z1/polite.o \
../obj_z1/print-stats.o \
../obj_z1/process.o \
../obj_z1/procinit.o \
../obj_z1/profile.o \
../obj_z1/psock.o \
../obj_z1/queuebuf.o \
../obj_z1/radio-sensor.o \
../obj_z1/random.o \
../obj_z1/relay-phidget.o \
../obj_z1/resolv.o \
../obj_z1/rime.o \
../obj_z1/rimeaddr.o \
../obj_z1/rimestats.o \
../obj_z1/ringbuf.o \
../obj_z1/rmh.o \
../obj_z1/route-discovery.o \
../obj_z1/route.o \
../obj_z1/rtimer-arch.o \
../obj_z1/rtimer.o \
../obj_z1/rucb.o \
../obj_z1/rudolph0.o \
../obj_z1/rudolph1.o \
../obj_z1/rudolph2.o \
../obj_z1/runicast.o \
../obj_z1/semantik.o \
../obj_z1/sensors.o \
../obj_z1/serial-line.o \
../obj_z1/sht11-sensor.o \
../obj_z1/sht11.o \
../obj_z1/sicslowmac.o \
../obj_z1/simple-udp.o \
../obj_z1/sky-sensors.o \
../obj_z1/slip.o \
../obj_z1/slip_uart0.o \
../obj_z1/spi.o \
../obj_z1/stbroadcast.o \
../obj_z1/stimer.o \
../obj_z1/stunicast.o \
../obj_z1/symbols.o \
../obj_z1/symtab.o \
../obj_z1/tcpdump.o \
../obj_z1/tcpip.o \
../obj_z1/temperature-sensor.o \
../obj_z1/timer.o \
../obj_z1/timesynch.o \
../obj_z1/timetable-aggregate.o \
../obj_z1/timetable.o \
../obj_z1/tmp102.o \
../obj_z1/trickle.o \
../obj_z1/uaodv-rt.o \
../obj_z1/uaodv.o \
../obj_z1/uart0-putchar.o \
../obj_z1/uart0.o \
../obj_z1/uip-debug.o \
../obj_z1/uip-fw-drv.o \
../obj_z1/uip-fw.o \
../obj_z1/uip-ipchksum.o \
../obj_z1/uip-neighbor.o \
../obj_z1/uip-over-mesh.o \
../obj_z1/uip-split.o \
../obj_z1/uip-udp-packet.o \
../obj_z1/uip.o \
../obj_z1/uip_arp.o \
../obj_z1/uiplib.o \
../obj_z1/unicast.o \
../obj_z1/util.o \
../obj_z1/watchdog.o \
../obj_z1/xmac.o \
../obj_z1/xmem.o \
../obj_z1/z1-phidgets.o 


# Each subdirectory must supply rules for building sources it contributes

